// This file was generated by [ts-rs](https://github.com/Aleph-Alpha/ts-rs). Do not edit this file manually.

/**
 * Per-participant lifecycle (§10.4) — the FSM's participant states.
 */
export type CallParticipantState = "ringing" | "joined" | "declined" | "left";
