// This file was generated by [ts-rs](https://github.com/Aleph-Alpha/ts-rs). Do not edit this file manually.

/**
 * Session lifecycle (§10.4) — the FSM's session states. `ringing` until the
 * first accept, `active` while ≥ 1 participant is joined, `ended` is terminal
 * (nothing leaves it).
 */
export type CallSessionState = "ringing" | "active" | "ended";
