// This file was generated by [ts-rs](https://github.com/Aleph-Alpha/ts-rs). Do not edit this file manually.
import type { MessagePreview } from "./MessagePreview";

/**
 * One row of the `channels.list` snapshot: the channel, the caller's own
 * watermarks, and a last-message preview.
 */
export type ChannelSummary = { channel_id: string, kind: string, name: string | null, last_seq: number, last_read_seq: number, last_delivered_seq: number, muted: boolean, last_message: MessagePreview | null, 
/**
 * For `dm` channels: the other party's last-seen (RFC 3339), gated on
 * their `share_presence` — `null` for groups, or when they don't share
 * (§10.2). Read-time honored, so a presence toggle takes effect on the
 * next list.
 */
last_seen_at: string | null, };
