// This file was generated by [ts-rs](https://github.com/Aleph-Alpha/ts-rs). Do not edit this file manually.

/**
 * One member of a channel (`channels.members`, §10.2): character id + when they
 * joined. Membership-gated read; carries no phone number (the §10.7 privacy
 * boundary), only the character id a co-member already sees in every message,
 * receipt, and `channels.member` event.
 */
export type ChannelMember = { character_id: string, joined_at: string, };
