// This file was generated by [ts-rs](https://github.com/Aleph-Alpha/ts-rs). Do not edit this file manually.

export type CharacterInfo = { id: string, framework_ref: string, 
/**
 * Plain `Option`: serde emits `null` (not absent), so TS is `string | null`.
 */
number: string | null, share_presence: boolean, };
