// This file was generated by [ts-rs](https://github.com/Aleph-Alpha/ts-rs). Do not edit this file manually.

/**
 * Client→server frame. On the wire the command flattens into the frame:
 * `{ "id": 7, "cmd": "sub", "payload": { ... } }` (OPN-CORE.md §7).
 */
export type ClientFrame = { 
/**
 * Client-chosen correlation id, echoed back as `reply_to` in the ack.
 * JSON number on the wire (clients never approach 2^53 frames).
 */
id: number, } & ({ "cmd": "sub", "payload": { topic: string, last_seq: number | null, } } | { "cmd": "unsub", "payload": { topic: string, } } | { "cmd": "auth_refresh" });
