// This file was generated by [ts-rs](https://github.com/Aleph-Alpha/ts-rs). Do not edit this file manually.
import type { MessageBody } from "./MessageBody";
import type { SettingsScope } from "./SettingsScope";

/**
 * Client→server frame. On the wire the command flattens into the frame:
 * `{ "id": 7, "cmd": "sub", "payload": { ... } }` (OPN-CORE.md §7).
 */
export type ClientFrame = { 
/**
 * Client-chosen correlation id, echoed back as `reply_to` in the ack.
 * JSON number on the wire (clients never approach 2^53 frames).
 */
id: number, } & ({ "cmd": "auth", "payload": { token: string, } } | { "cmd": "sub", "payload": { topic: string, last_seq: number | null, } } | { "cmd": "unsub", "payload": { topic: string, } } | { "cmd": "auth.refresh" } | { "cmd": "identity.me" } | { "cmd": "identity.app_login", "payload": { app_id: string, account_id: string, } } | { "cmd": "identity.get_settings", "payload": { scope: SettingsScope, } } | { "cmd": "identity.set_settings", "payload": { scope: SettingsScope, 
/**
 * Whole-document replace, opaque to Core.
 */
patch: unknown, } } | { "cmd": "identity.set_share_presence", "payload": { on: boolean, } } | { "cmd": "channels.send", "payload": { channel_id: string, client_uuid: string, body: MessageBody, } } | { "cmd": "channels.open_direct", "payload": { number: string, } } | { "cmd": "channels.create", "payload": { name: string | null, members: Array<string>, } } | { "cmd": "channels.list" } | { "cmd": "channels.mark_delivered", "payload": { channel_id: string, up_to_seq: number, } } | { "cmd": "channels.mark_read", "payload": { channel_id: string, up_to_seq: number, } } | { "cmd": "channels.typing", "payload": { channel_id: string, } } | { "cmd": "channels.react", "payload": { channel_id: string, message_id: string, emoji: string, } } | { "cmd": "channels.unreact", "payload": { channel_id: string, message_id: string, emoji: string, } } | { "cmd": "channels.pin", "payload": { channel_id: string, message_id: string, } } | { "cmd": "channels.unpin", "payload": { channel_id: string, message_id: string, } } | { "cmd": "channels.member_add", "payload": { channel_id: string, character_id: string, } } | { "cmd": "channels.member_remove", "payload": { channel_id: string, character_id: string, } } | { "cmd": "notify.seen", "payload": { ids: Array<string>, } } | { "cmd": "notify.clear" });
