// This file was generated by [ts-rs](https://github.com/Aleph-Alpha/ts-rs). Do not edit this file manually.

/**
 * Every client→server command. Serde does the routing, `match` does the
 * dispatch, the compiler does the exhaustiveness (OPN-CORE.md §7).
 *
 * Wire shape: `{ "cmd": "<snake_case name>", "payload": { ... } }`
 * (unit variants omit `payload`).
 */
export type Cmd = { "cmd": "sub", "payload": { topic: string, last_seq: number | null, } } | { "cmd": "unsub", "payload": { topic: string, } } | { "cmd": "auth_refresh" };
