// This file was generated by [ts-rs](https://github.com/Aleph-Alpha/ts-rs). Do not edit this file manually.
import type { SettingsScope } from "./SettingsScope";

/**
 * Every client→server command. Serde does the routing, `match` does the
 * dispatch, the compiler does the exhaustiveness (OPN-CORE.md §7).
 *
 * Wire shape: `{ "cmd": "<name>", "payload": { ... } }` (unit variants omit
 * `payload`). `sub`/`unsub` come from the enum-level `rename_all`; the
 * dotted `auth.refresh`/`identity.*` names are pinned per-variant to match
 * the design doc (OPN-CORE.md §10.1).
 */
export type Cmd = { "cmd": "auth", "payload": { token: string, } } | { "cmd": "sub", "payload": { topic: string, last_seq: number | null, } } | { "cmd": "unsub", "payload": { topic: string, } } | { "cmd": "auth.refresh" } | { "cmd": "identity.me" } | { "cmd": "identity.app_login", "payload": { app_id: string, account_id: string, } } | { "cmd": "identity.get_settings", "payload": { scope: SettingsScope, } } | { "cmd": "identity.set_settings", "payload": { scope: SettingsScope, 
/**
 * Whole-document replace, opaque to Core.
 */
patch: unknown, } } | { "cmd": "identity.set_share_presence", "payload": { on: boolean, } };
