// This file was generated by [ts-rs](https://github.com/Aleph-Alpha/ts-rs). Do not edit this file manually.

/**
 * One comment in a post-detail page (§10.3, Sprint 8 part B). `body` is opaque,
 * size-capped like a post; newest-first on the cursor idiom.
 */
export type CommentItem = { id: string, post_id: string, author_account: string, body: unknown, created_at: string, };
