// This file was generated by [ts-rs](https://github.com/Aleph-Alpha/ts-rs). Do not edit this file manually.

/**
 * One row of the caller's private contact book (`directory.contacts`).
 * Contacts point at raw numbers; a number resolves to a character only at
 * action time, so this carries no character id.
 */
export type ContactItem = { number: string, display_name: string, 
/**
 * A live media owned by the caller, validated at write time (§10.7).
 */
avatar_media: string | null, meta: unknown, created_at: string, };
