// This file was generated by [ts-rs](https://github.com/Aleph-Alpha/ts-rs). Do not edit this file manually.

/**
 * Every server→client pushed event. Same tagging idiom as `Cmd`.
 *
 * Variants land with their primitives (first ones in Sprint 2/3); the enum
 * exists from day one so the contracts drift gate and the coverage
 * match-test exist from day one.
 */
export type Evt = { "evt": "presence.state", "payload": { character_id: string, online: boolean | null, 
/**
 * RFC 3339; present only in `online: false` transitions.
 */
last_seen_at: string | null, } };
