// This file was generated by [ts-rs](https://github.com/Aleph-Alpha/ts-rs). Do not edit this file manually.
import type { NotifyClass } from "./NotifyClass";

/**
 * Every server→client pushed event. Same tagging idiom as `Cmd`.
 *
 * Variants land with their primitives (first ones in Sprint 2/3); the enum
 * exists from day one so the contracts drift gate and the coverage
 * match-test exist from day one.
 */
export type Evt = { "evt": "presence.state", "payload": { character_id: string, online: boolean | null, 
/**
 * RFC 3339; present only in `online: false` transitions.
 */
last_seen_at: string | null, } } | { "evt": "channels.message", "payload": { channel_id: string, message_id: string, seq: number, sender: string, body: unknown, 
/**
 * RFC 3339 server timestamp.
 */
at: string, } } | { "evt": "notify.event", "payload": { app_id: string, kind: string, class: NotifyClass, payload: unknown, } };
