// This file was generated by [ts-rs](https://github.com/Aleph-Alpha/ts-rs). Do not edit this file manually.

/**
 * One post in a feed read page (home/profile/hashtag timelines, post detail;
 * §10.3, Sprint 8 part B). `body` is the opaque app-owned doc Core caps but
 * never interprets; `media_ids` were validated owned+live at write time (a
 * later-deleted media renders missing). `like_count`/`comment_count` are the
 * denormalized exact counters. Newest-first on the shared cursor idiom (CDR-7).
 */
export type PostItem = { id: string, app_id: string, author_account: string, body: unknown, media_ids: string[], like_count: number, comment_count: number, created_at: string, };
