// This file was generated by [ts-rs](https://github.com/Aleph-Alpha/ts-rs). Do not edit this file manually.

/**
 * One reaction on a history row (§10.2): the emoji and who reacted. Same
 * granularity as the live `channels.reaction` event, so a cold-load rebuilds
 * the exact same reaction map the live stream would.
 */
export type ReactionItem = { emoji: string, character_id: string, };
