// This file was generated by [ts-rs](https://github.com/Aleph-Alpha/ts-rs). Do not edit this file manually.
import type { Err } from "./Err";
import type { JsonValue } from "./serde_json/JsonValue";

/**
 * Server→client frame. Untagged on the wire: an ack always carries
 * `reply_to`, a push always carries `topic` + `evt` — the client
 * distinguishes by field presence.
 */
export type ServerMsg = { reply_to: number, ok: boolean, 
/**
 * Typed per-command ack payload. `serde_json::Value` only until the
 * command lands a concrete type (roadmap Sprint 0 rule) — never
 * beyond the sprint that adds the command.
 */
payload?: JsonValue, err?: Err, } | { topic: string, } & ({ "evt": "presence.state", "payload": { character_id: string, online: boolean | null, 
/**
 * RFC 3339; present only in `online: false` transitions.
 */
last_seen_at: string | null, } });
