// This file was generated by [ts-rs](https://github.com/Aleph-Alpha/ts-rs). Do not edit this file manually.
import type { CharacterInfo } from "./CharacterInfo";
import type { DeviceInfo } from "./DeviceInfo";

export type SessionMintResponse = { token: string, session_id: string, character: CharacterInfo, device: DeviceInfo, };
