// This file was generated by [ts-rs](https://github.com/Aleph-Alpha/ts-rs). Do not edit this file manually.

/**
 * Call media topology (opn-group-calls.md G0). `p2p` — 1:1 calls, media flows
 * peer-to-peer and Core relays only signaling (Sprint 6). `sfu` — group calls,
 * media forwards through the LiveKit sidecar. Carried on every call snapshot
 * from day one so a future topology change never breaks a pinned client
 * (additive-only, contracts-semver.md). `p2p` is the default, so an old
 * snapshot without the field deserializes unchanged.
 */
export type Topology = "p2p" | "sfu";
