// This file was generated by [ts-rs](https://github.com/Aleph-Alpha/ts-rs). Do not edit this file manually.

/**
 * One transfer in a `GET /v1/ledger/history` page (§10.5). Raw `from`/`to`
 * account ids + amount; the client owns its own account ids and renders
 * direction from them. `kind` is `transfer` (a `ledger.transfer`) or `capture`
 * (a settled hold). Never carries a balance — history is the journal, not a
 * running total.
 */
export type TransferItem = { id: string, from_account: string, to_account: string, amount: number, kind: string, created_at: string, };
