// This file was generated by [ts-rs](https://github.com/Aleph-Alpha/ts-rs). Do not edit this file manually.

/**
 * One presigned S3 POST target (§10.6). The client POSTs a multipart form to
 * `url` with every entry of `fields` plus a trailing `file` part — nothing
 * else. The cap is MinIO's, enforced by the policy inside `fields`, so a
 * cheating client cannot lift it.
 */
export type UploadTarget = { 
/**
 * `original` or `thumb`.
 */
role: string, url: string, fields: Record<string, string>, };
