// This file was generated by [ts-rs](https://github.com/Aleph-Alpha/ts-rs). Do not edit this file manually.
import type { UploadTarget } from "./UploadTarget";

/**
 * `media.request_upload` ack (§10.6): the new media id and one or two POST
 * targets (thumb present for photo/video).
 */
export type UploadTicket = { media_id: string, targets: Array<UploadTarget>, };
