// This file was generated by [ts-rs](https://github.com/Aleph-Alpha/ts-rs). Do not edit this file manually.

/**
 * Voice-target action on the tenant link (§5, §10.4): `set_targets` names the
 * characters whose game-voice Core wants bound for a call; `clear` tears them
 * down when the call ends. Down-only (Core → FXServer), tenant-scoped.
 */
export type VoiceAction = "set_targets" | "clear";
