// This file was generated by [ts-rs](https://github.com/Aleph-Alpha/ts-rs). Do not edit this file manually.

/**
 * One message row in a `GET /v1/channels/:id/messages` history page (§6).
 * Seq-keyed (not the time cursor) — seq is already public in this contract.
 */
export type MessageItem = { message_id: string, seq: number, sender: string, body: unknown, at: string, };
