// This file was generated by [ts-rs](https://github.com/Aleph-Alpha/ts-rs). Do not edit this file manually.

/**
 * Semantic urgency of a notification, chosen by the emitting primitive
 * (calls → ring, messages → alert, receipts/likes → silent). Core mandates
 * zero presentation — the shell maps this to toast/badge/ring.
 */
export type NotifyClass = "ring" | "alert" | "silent";
