// This file was generated by [ts-rs](https://github.com/Aleph-Alpha/ts-rs). Do not edit this file manually.
import type { CallKind } from "./CallKind";
import type { CallParticipant } from "./CallParticipant";
import type { CallSessionState } from "./CallSessionState";

/**
 * One active call in the `GET /v1/tenants/self/calls/active` re-sync (§5): the
 * tenant link reads these on (re)connect to rebuild voice targets after a drop.
 * Same shape as a `calls.state` snapshot minus the ICE config.
 */
export type ActiveCall = { call_id: string, kind: CallKind, state: CallSessionState, participants: Array<CallParticipant>, };
