// This file was generated by [ts-rs](https://github.com/Aleph-Alpha/ts-rs). Do not edit this file manually.

/**
 * Call medium (§10.4). `calls.start`'s `video: bool` maps here — `false` →
 * voice, `true` → video. Voice audio always rides pma-voice; WebRTC carries
 * video only.
 */
export type CallKind = "voice" | "video";
