// This file was generated by [ts-rs](https://github.com/Aleph-Alpha/ts-rs). Do not edit this file manually.
import type { ErrCode } from "./ErrCode";

/**
 * Wire error body: `{ "code": "...", "msg": "..." }`. `msg` is
 * developer-facing; UI copy is the app's job keyed off `code`.
 */
export type Err = { code: ErrCode, msg: string, };
