// This file was generated by [ts-rs](https://github.com/Aleph-Alpha/ts-rs). Do not edit this file manually.

/**
 * The closed error-code set (OPN-CORE.md §7). Adding a variant is a
 * contracts-major event.
 */
export type ErrCode = "unauthorized" | "forbidden" | "not_found" | "invalid" | "conflict" | "rate_limited" | "too_large" | "internal";
