// This file was generated by [ts-rs](https://github.com/Aleph-Alpha/ts-rs). Do not edit this file manually.
import type { NotifyClass } from "./NotifyClass";

/**
 * One stored notification, read via `GET /v1/notify/inbox` after login.
 */
export type InboxItem = { id: string, app_id: string, kind: string, class: NotifyClass, payload: unknown, seen_at: string | null, created_at: string, };
