// This file was generated by [ts-rs](https://github.com/Aleph-Alpha/ts-rs). Do not edit this file manually.

/**
 * One listing (`directory.listings`, §10.7): an app-scoped ad/posting with an
 * optional TTL. `contact_number` is the number a reader would call — free-form,
 * not a resolved character.
 */
export type ListingItem = { id: string, app_id: string, kind: string, title: string, body: unknown, contact_number: string, created_at: string, expires_at: string | null, };
