// This file was generated by [ts-rs](https://github.com/Aleph-Alpha/ts-rs). Do not edit this file manually.

/**
 * One message body — the same shape for every channel kind (§10.2); apps
 * interpret it. At least one of `text | media_ids | gif_url` must be present
 * (Core validates at send). `meta` is an opaque app-owned bag.
 */
export type MessageBody = { text: string | null, media_ids: string[] | null, gif_url: string | null, meta: unknown, };
