// This file was generated by [ts-rs](https://github.com/Aleph-Alpha/ts-rs). Do not edit this file manually.

/**
 * Newest message in a channel, for the `channels.list` snapshot preview.
 */
export type MessagePreview = { seq: number, sender: string, body: unknown, at: string, };
