// This file was generated by [ts-rs](https://github.com/Aleph-Alpha/ts-rs). Do not edit this file manually.

/**
 * Which watermark a `channels.receipt` event carries (§10.2). `delivered` is
 * device-received; `read` is user-read. Both monotonic, both watermark-only
 * (never per-message rows).
 */
export type ReceiptKind = "delivered" | "read";
