// This file was generated by [ts-rs](https://github.com/Aleph-Alpha/ts-rs). Do not edit this file manually.

/**
 * Which settings document an `identity.*_settings` command targets.
 */
export type SettingsScope = "device" | "character";
